name: Construir e Enviar Imagem para o Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download dos arquivos do repositório
      uses: actions/checkout@v2

    - name: Fazer login no Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWD }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

    - name: Instalar Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
    - name: Construir imagem Docker
      run: docker-compose build

    - name: Tag da imagem Docker
      run: |
        docker tag fastapi-com-postgresql_fastapi:latest mmayumi/fastapi-app:latest
        docker tag fastapi-com-postgresql_fastapi:latest mmayumi/fastapi-app:v${{ github.run_number }}

    - name: Enviar imagem Docker
      run: |
        docker push mmayumi/fastapi-app:latest
        docker push mmayumi/fastapi-app:v${{ github.run_number }}

    - name: Executar Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: 'docker.io/mmayumi/fastapi-app:v${{ github.run_number }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Enviar resultados do Trivy para a aba de Segurança do Github
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        
    - name: Fazer logout do Docker Hub
      run: docker logout
