name: Construir e Enviar Imagem para o Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download dos arquivos do repositório
      uses: actions/checkout@v2

    - name: Fazer login no Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWD }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

    - name: Construir imagem Docker
      run: docker build . -t mmayumi/fastapi-app:latest

    - name: Enviar imagem Docker
      run: docker push mmayumi/fastapi-app:latest

    - name: Fazer logout do Docker Hub
      run: docker logout

    - name: Término
      run: echo "Imagem enviada ao Docker Hub com sucesso"